dist: xenial

language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- coverage run --branch --source=. ./tests.py
- coverage xml
- python-codacy-coverage -r coverage.xml
- python -m unittest tests.py
deploy:
  provider: heroku
  app: decide-palkia-bot
  strategy: git
  api_key:
    secure: G+loA3DMc0B+a2tkMDRboAiU2Wunm4wEp2y0d/NIwlx1bQd7JB+Cael2b0NotzMVwXNIZBOechoRY+F8UW4q+Yx8QkTAAm1A7S0LhFyNnVAWKtGXyNntIjNb/nF0BrHcrEhcVOiFTO1TBPyhPuJaoogV7IAhSpFkUl0jWYeEbdK+A4Rtw0HFmTOvOI5g71thLREiUWaWXKHQYUhmlhBAEaCMSANd6RULALXUm02u8Keo3FgJoPdDrYlbQwpdIl9gMHswNS8s4HDeRsK/vBOyc5cRiltGMMQLOD2u7e3ur/UbF90z1DTvrPkXMiUhF00795Q2EfGJAqhWVIP4CxVWxm9BU+Wca3ou7v370OPW0qnbbf4JIzqOqrFsAtFtB8lkqTO/KJqyvyxZxMrH36BYig64yJ/WPyLGj1nNLTeJhZAmfobkKAeCyTrLl1RhT0X0Dtsh+ZK837QmC+jGodC24zhQVlqpznj7BQnF5h6M1htLpfslShAhuHZk47c8aHorofBk57C8wVSr4xGPNzvc28YiAh+GdddRGHFMEo08pUi42H/Gu6wlqDT+dg5OAI6eHHKgzQW8HyiNf/zgRpNswVWVF2Sd7hhNL6L1WFPzFRdlTMvkLCqIlft2RFyWu5TLQUe3idSNSBnoF59A+CgcZ/xKZwnTKAT2eRNjIufglUo=
  on:
    branch: develop