dist: xenial

language: python
python:
  - "3.7"
install:
  - pip install pyTelegramBotAPI
  - pip install requests
  - pip install codacy-coverage
  - pip install coverage
script:
  - python -m unittest tests.py