dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- coverage run --branch --source=. ./tests.py
- coverage xml
- python-codacy-coverage -r coverage.xml
- python -m unittest tests.py
deploy:
  provider: heroku
  app: decide-palkia-bot-integration
  strategy: git
  on:
    branch: master
  api_key:
    secure: dnx5w+DAPHKjtVDfo+U92QreTcazaJjU4pNm4qvNapshrsgFsFR+3lOoSVsHO+aBN19DAh7lMIySReHW+YMSD/UUMideFT9nK9hsKPFof9RVcw4QjzUr3DvIeWReA02cpRn+nNnD8kvSYVy/3P/7HKEQ9GuUvZsXMfbXH8XeyDRr45tc7uxD0Sb8xqTCfF+3EZwNN8kQd5iUeoO84Tjyf84mi5QOjTiKEHaM3KRpKAJ3/ivwgllJPto+3GmbDKw0NL3hLaiXJMm5i2GSttYADhaW+f04l6u8U0gTl3CNDrSmRF8i/vQ4bNUJ5uKeRLxu5f7gC71bYzWW5I9FvfVfk9fLE967akEDu6lfFoT8cvGeI1bwC6BDakT3v5/DUTvB5X21CtN6h8NTU8j4x7vbb7SgPJtSShR4U8hbWKe/KVWZGUhAD+iHTLSn7aECVS4E7OMJqsAITqk5z0T4U0is1vYlOzMaXxL86QAXH6fTJl5dwCx+6VKYK+AYBxi1ofy03gDuBIB+R62hjKLYy/GTUIx62MVZxCUjFJekuOtsRT9Z7xPs9/Igeaal7pXfK3lz4CNZ1XMZGj9ZyjHKrFHYisGSJKsaKMzGb7JYhMbRPOCj95cyF4VX36cLLDVH7Kb0UjXk8XaUr6/uFYgc7/3TRi8Q5iAJcY8LPh4a8+AepkE=