dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- coverage run --branch --source=. ./tests.py
- coverage xml
- python-codacy-coverage -r coverage.xml
- python -m unittest tests.py
deploy:
  provider: heroku
  app: decide-palkia-bot
  strategy: git
  on:
    branch: develop
  api_key:
    secure: oiFngaeEoxwUCVFLbEY8z9IfgooRhXXIvEihGZU2ftyDJSOQV/ib7tRWAvnjUM9JgQx3ey9SqqVf2pRHiaJCx/KomndMIQWx8M2IZ+SIzvQkITNbxurI0jyTDbh7Z5UT3DfBxiAGERGILt5XdWIvjkEHR7R2CIBwKP9894FnZZJJEWuyY5bIsghlJ33PcU0h3Ne664ZTi+7vn9RXUQVsVBQyL3kW5iPG0BQgXSTBdQsIkAsI4UHV3gSE0esEB+EYTfXkm0cL4Ku0zoino+tlGBi0U2vY34C0Xg/7QhxmS0pLVUac7RK/Jl/puRrMFr9iYrIMV9vTbCq8I7/mIXBz+4gBYEhjp3RfLjZDfOmt7IXyhiYqegpYtOZUwGhLIwlDBKtNwbJ20Fgu5+AfEQjX18uePqkBjy1j3GAdV3EzicfFRK+ZrVvja8rgaFxLHX66kR/qg6TlzAaNtsWQ37lPuV+Fjb4x+5clGTMHV4SiatwiZXr6BilVkGNFlyLnSWboQ4Dr59WA3MMBcKQs/v0wouoxEK3nW4ABy1EcHU6dqFiyeb/MLTghto+N7juuXxMcmCLqItbiacBm5nZrY42nCs+Gl2JSWQEx3T43PK7+jb0oCzDBgLvFQ2zStx55NB/Y03nfxa+E4oEEAwiFBDn0wMRuANM98q500geSEptNCdg=